name: stereo_vision
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - opencv-python==4.12.0.88
    - opencv-contrib-python==4.12.0.88
    - numpy==2.2.6
    - matplotlib==3.10.3
    - imutils==0.5.4
    - mediapipe==0.10.14
    - scipy==1.16.1
